
env:
  CI: false
on: 
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
name: 🚀 Deploy Tropa Digital
jobs:
  web-deploy:
    name: 🎉 Baixando Dependencias no servidor
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Baixando ultima versão do código
      uses: actions/checkout@v2
      

    - name: Usando Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: 🔨 Gerando Build
      run: |
        npm install
        npm run build
    - name: 🔗 Iniciando conexão FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.ftp_host}}
        username: ${{secrets.ftp_user}}
        password: ${{secrets.ftp_password}}
        server-dir: /domains/frontendtropa.com.br/public_html/21livedeploy/
